### ISSUE TITLE
image-from-csv: colour maps for scalar

### ISSUE THREAD

**Issue by junderwood** [acfr/snark#112]
Currently supported fields are "grey" and "r,g,b"
Would be nice to have scalar with colourmap=hot, etc as with view-points.
An alterative would be to have another utility called scalar-to-rgb, which would do the job separately to image-from-csv

**Comment by vlaskine** [comment]
added to the backlog; in future, could you please add the enhancement suggestions to the backlog? it adds too much work to track them at two places
