### ISSUE TITLE
 fatal error: dc1394/dc1394.h: No such file or directory

### ISSUE THREAD

**Issue by kerimyener** [acfr/snark#129]
hi fellow,
I have a problem while I try to compile your code. Could you help me out how can I solve this problem

**Comment by navidp** [comment]
That is a header file for camera libraries.
You need to either install the library or disable the build option.
To install the library on linux, do something like:
sudo apt-get install libdc1394-22-dev
To disable the build option, run ccmake . on the build directory and set snark_build_sensors_dc1394 to OFF.
