### ISSUE TITLE
spherical_geometry\coordinates.h: windows compile error

### ISSUE THREAD

**Issue by junderwood** [acfr/snark#95]
5>c:\users\j.underwood\code\cpp\source\snark\math\spherical_geometry\coordinates.h(57): error C2226: syntax error : unexpected type 'Eigen::Vector3d'
5>c:\users\j.underwood\code\cpp\source\snark\math\spherical_geometry\coordinates.h(57): error C2238: unexpected token(s) preceding ';'
5>c:\users\j.underwood\code\cpp\source\snark\math\spherical_geometry\coordinates.h(72): error C2226: syntax error : unexpected type 'snark::spherical::coordinates'
5>c:\users\j.underwood\code\cpp\source\snark\math\spherical_geometry\coordinates.h(72): error C2238: unexpected token(s) preceding ';'

**Comment by vlaskine** [comment]
@navidp : could you please fix it? the problem is that on windows (sigh) "near" is a reserved word (i think)

the quick fix would be: rename the methods from "near()" to "is_near()" in snark::spherical::coordinates; and then fix compilation in aero

thank you!

**Comment by navidp** [comment]
I renamed it to is_near. let me know if it solves the problem on windows.

**Comment by junderwood** [comment]
Thanks, that solved it.
